#!/usr/bin/env python3
"""Generate version.js for the Pixiv Novel Translator extension.

Writes the current git commit short hash into version.js so the
extension UI can display the exact build revision.
"""
import subprocess
import os
import sys

EXT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'pixiv-novel-translator')


def git_short_commit() -> str:
    try:
        out = subprocess.run(
            ['git', 'rev-parse', '--short', 'HEAD'],
            capture_output=True, text=True, check=True,
            cwd=os.path.dirname(os.path.abspath(__file__)),
        )
        return out.stdout.strip()
    except Exception:
        return 'unknown'


def main():
    commit = git_short_commit()
    content = (
        '// Generated by build_extension.py — do not edit.\n'
        "const EXTENSION_VERSION = '1.1.0+" + commit + "';\n"
        "const EXTENSION_COMMIT = '" + commit + "';\n"
    )
    out = os.path.join(EXT_DIR, 'version.js')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(content)
    print(f'version.js written: {commit}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
